language: node_js
node_js:
- '7'
dist: trusty
before_script:
- npm install
- npm run setup
- mkdir dist
- mkdir dist/js
script:
- npm run build
- npm run test
cache:
  directories:
  - node_modules
env:
- CXX=g++-4.8 CC=gcc-4.8
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: ./dist
    github_token: $GITHUB_TOKEN
    target_branch: gh-pages
    fqdn: jsstringconverter.bbody.io
    repo: bbody/MultilineJavaScriptConverter
    on:
      branch: master
after_success: npm run coverage