language: node_js
node_js:
- '7'
dist: trusty
before_script:
- npm install
script:
- gulp test:karma
cache:
  directories:
  - node_modules
env:
- CXX=g++-4.8 CC=gcc-4.8
before_deploy:
  - npm run build
  - npm run test